# Generated by Django 5.2.7 on 2025-10-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='static/images/default.jpeg', upload_to=''),
        ),
    ]
