# Generated by Django 5.2.7 on 2025-11-14 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_participant_remove_event_image_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
