# Generated by Django 5.2.7 on 2025-11-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, default='events_asset/default_event.jpg', null=True, upload_to='events_asset/'),
        ),
    ]
